include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - "**.g.dart"
    - "**.gr.dart"
    - "**.freezed.dart"
    - "**.config.dart"
linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
