name: {{project_name.snakeCase()}}
description: {{description.sentenceCase()}}

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # Networking
  dio: ^5.1.2
  pretty_dio_logger: ^1.3.1

  # Routing
  auto_route: ^5.0.4

  # Utility
  intl: ^0.18.0

  # Dependency Injection
  injectable: ^2.1.1
  get_it: ^7.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linter
  very_good_analysis: ^5.0.0+1

  # Code Generation
  build_runner: ^2.4.4
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
